/** After a wave: compact unused letters, fill from the top, seed 3–6 straight words. */

import {
  DIRS,
  cellKey,
  inBounds,
  locatePlacements,
  type Cell,
  type Placement,
} from './model';

export const WAVE_MIN_WORDS = 3;
export const WAVE_MAX_WORDS = 6;

/** 6 words for 5 waves, then drop by 1 every 5 waves. Floor is 3. */
export function targetWordCount(wave: number): number {
  const n = Math.max(1, wave);
  return Math.max(WAVE_MIN_WORDS, WAVE_MAX_WORDS - Math.floor((n - 1) / 5));
}

/** After wave 20: 1 word hides a letter. +1 word every 5 waves, max 3. */
export function maskedHintCount(wave: number): number {
  if (wave < 20) return 0;
  return Math.min(3, 1 + Math.floor((wave - 20) / 5));
}

export type WordTheme = {
  title: string;
  words: readonly string[];
};

/** Pop-style clue: one category per wave. Bonus words still use the full lexicon. */
export const WAVE_THEMES: readonly WordTheme[] = [
  {
    title: 'From the Toy Store',
    words: ['BALL', 'DOLL', 'KITE', 'TOY', 'GAME', 'BLOCK', 'ROBOT', 'TRAIN', 'PUPPET', 'CARD', 'DICE', 'BEAR'],
  },
  {
    title: 'On the Farm',
    words: ['COW', 'PIG', 'HEN', 'HAY', 'BARN', 'CORN', 'FARM', 'GOAT', 'HORSE', 'DUCK', 'SEED', 'YARD'],
  },
  {
    title: 'In the Kitchen',
    words: ['PAN', 'POT', 'CUP', 'TEA', 'CAKE', 'COOK', 'OVEN', 'FORK', 'SPOON', 'BREAD', 'SUGAR', 'PLATE'],
  },
  {
    title: 'Ocean Life',
    words: ['SEA', 'FISH', 'WAVE', 'BOAT', 'SHIP', 'CRAB', 'REEF', 'SHELL', 'WHALE', 'OCEAN', 'CORAL', 'SHARK'],
  },
  {
    title: 'In the Forest',
    words: ['TREE', 'LEAF', 'BIRD', 'DEER', 'WOLF', 'BEAR', 'NEST', 'WOOD', 'FROG', 'MOSS', 'PINE', 'OWL'],
  },
  {
    title: 'Weather',
    words: ['SUN', 'SKY', 'RAIN', 'SNOW', 'WIND', 'HAIL', 'HEAT', 'COLD', 'CLOUD', 'STORM', 'MIST', 'FOG'],
  },
  {
    title: 'Colors',
    words: ['RED', 'BLUE', 'PINK', 'GOLD', 'GRAY', 'TEAL', 'GREEN', 'BLACK', 'WHITE', 'BROWN', 'IVORY', 'AMBER'],
  },
  {
    title: 'The Body',
    words: ['ARM', 'LEG', 'EAR', 'EYE', 'LIP', 'HAND', 'NOSE', 'FACE', 'HAIR', 'FOOT', 'NECK', 'SKIN'],
  },
  {
    title: 'Music',
    words: ['SONG', 'NOTE', 'BAND', 'DRUM', 'BELL', 'TUNE', 'BEAT', 'PIANO', 'GUITAR', 'FLUTE', 'CHOIR', 'MUSIC'],
  },
  {
    title: 'Outer Space',
    words: ['STAR', 'MOON', 'SUN', 'MARS', 'ROCK', 'ORBIT', 'COMET', 'EARTH', 'SPACE', 'NOVA', 'DUST', 'VOID'],
  },
  {
    title: 'Sweet Snacks',
    words: ['CAKE', 'PIE', 'JAM', 'NUT', 'CANDY', 'SUGAR', 'COOKIE', 'HONEY', 'COCOA', 'MINT', 'TAFFY', 'FUDGE'],
  },
  {
    title: 'At School',
    words: ['PEN', 'INK', 'BOOK', 'DESK', 'NOTE', 'EXAM', 'QUIZ', 'PAPER', 'PENCIL', 'CLASS', 'RULER', 'CHALK'],
  },
];

const THEME_WORDS = WAVE_THEMES.flatMap((t) => t.words);
/** Common words that can score as extras. Not used as themed targets. */
const BONUS_EXTRA = [
  'ACE', 'ADD', 'AGE', 'AGO', 'AID', 'AIM', 'AIR', 'ALL', 'AND', 'ANT', 'ANY',
  'APE', 'ARC', 'ARE', 'ARK', 'ARM', 'ART', 'ASH', 'ASK', 'AWE',
  'BAG', 'BAN', 'BAR', 'BAT', 'BAY', 'BED', 'BEE', 'BEG', 'BET', 'BID', 'BIG',
  'BIN', 'BIT', 'BOW', 'BOX', 'BOY', 'BUD', 'BUG', 'BUN', 'BUS', 'BUT', 'BUY',
  'CAB', 'CAN', 'CAP', 'CAR', 'CAT', 'COB', 'COD', 'COP', 'COT', 'CRY', 'CUB',
  'CUP', 'CUT', 'DAD', 'DAM', 'DAY', 'DEN', 'DEW', 'DID', 'DIE', 'DIG', 'DIM',
  'DIP', 'DOC', 'DOG', 'DOT', 'DRY', 'DUB', 'DUE', 'DUG', 'DYE',
  'EAR', 'EAT', 'EEL', 'EGG', 'ELF', 'ELK', 'ELM', 'EMU', 'END', 'ERA', 'EVE',
  'EWE', 'EYE', 'FAD', 'FAN', 'FAR', 'FAT', 'FAX', 'FED', 'FEW', 'FIG', 'FIN',
  'FIT', 'FIX', 'FLU', 'FLY', 'FOE', 'FOG', 'FOR', 'FOX', 'FRY', 'FUN', 'FUR',
  'GAG', 'GAP', 'GAS', 'GEL', 'GEM', 'GET', 'GIG', 'GIN', 'GOT', 'GUM', 'GUN',
  'GUT', 'GUY', 'GYM', 'HAD', 'HAM', 'HAS', 'HAT', 'HAY', 'HEN', 'HER', 'HID',
  'HIM', 'HIP', 'HIS', 'HIT', 'HOG', 'HOP', 'HOT', 'HOW', 'HUB', 'HUE', 'HUG',
  'HUM', 'HUT', 'ICE', 'ICY', 'ILL', 'INK', 'INN', 'ION', 'IRK', 'ITS',
  'JAM', 'JAR', 'JAW', 'JAY', 'JET', 'JOB', 'JOG', 'JOT', 'JOY',
  'KEG', 'KEY', 'KID', 'KIN', 'KIT', 'LAB', 'LAD', 'LAP', 'LAW', 'LAY', 'LED',
  'LEG', 'LET', 'LID', 'LIE', 'LIP', 'LIT', 'LOG', 'LOT', 'LOW',
  'MAD', 'MAN', 'MAP', 'MAT', 'MAX', 'MAY', 'MEN', 'MET', 'MIX', 'MOB', 'MOM',
  'MOP', 'MUD', 'MUG', 'NAG', 'NAP', 'NET', 'NEW', 'NIL', 'NIT', 'NOD', 'NOR',
  'NOT', 'NOW', 'NUN', 'NUT', 'OAK', 'OAR', 'OAT', 'ODD', 'OFF', 'OIL', 'OLD',
  'ONE', 'ORB', 'ORE', 'OUR', 'OUT', 'OWE', 'OWL', 'OWN',
  'PAD', 'PAL', 'PAN', 'PAT', 'PAW', 'PAY', 'PEA', 'PEG', 'PEN', 'PET', 'PEW',
  'PIE', 'PIG', 'PIN', 'PIT', 'PLY', 'POD', 'POP', 'POT', 'PRO', 'PRY', 'PUB',
  'PUN', 'PUP', 'PUT', 'RAG', 'RAM', 'RAN', 'RAP', 'RAT', 'RAW', 'RAY', 'RED',
  'RIB', 'RID', 'RIG', 'RIM', 'RIP', 'ROB', 'ROD', 'ROT', 'ROW', 'RUB', 'RUG',
  'RUM', 'RUN', 'RYE', 'SAD', 'SAG', 'SAP', 'SAT', 'SAW', 'SAY', 'SEA', 'SEE',
  'SET', 'SEW', 'SHE', 'SHY', 'SIN', 'SIP', 'SIR', 'SIT', 'SIX', 'SKI', 'SKY',
  'SLY', 'SOB', 'SOD', 'SON', 'SOW', 'SOY', 'SPA', 'SPY', 'SUN',
  'TAB', 'TAD', 'TAG', 'TAN', 'TAP', 'TAR', 'TAX', 'TEA', 'TEN', 'THE', 'TIE',
  'TIN', 'TIP', 'TOE', 'TON', 'TOO', 'TOP', 'TOW', 'TOY', 'TRY', 'TUB', 'TUG',
  'TWO', 'URN', 'USE', 'VAN', 'VAT', 'VET', 'VIA', 'VOW',
  'WAD', 'WAG', 'WAN', 'WAR', 'WAS', 'WAX', 'WAY', 'WEB', 'WED', 'WET', 'WHO',
  'WHY', 'WIG', 'WIN', 'WIT', 'WOK', 'WON', 'WOE', 'WOW',
  'YAK', 'YAM', 'YAP', 'YAW', 'YEA', 'YES', 'YET', 'YEW', 'YOU', 'ZAP', 'ZED',
  'ZIG', 'ZIP', 'ZIT', 'ZOO',
  'ABLE', 'ACID', 'AGED', 'AIDE', 'ALSO', 'AREA', 'ARMY', 'AUNT', 'AUTO', 'AWAY',
  'BABY', 'BACK', 'BAKE', 'BALD', 'BALM', 'BAND', 'BANG', 'BANK', 'BARE', 'BARK',
  'BARN', 'BASE', 'BATH', 'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEEF',
  'BEEN', 'BEER', 'BELL', 'BELT', 'BEND', 'BENT', 'BEST', 'BIKE', 'BILL', 'BIND',
  'BIRD', 'BITE', 'BLEW', 'BLOW', 'BLUE', 'BLUR', 'BOAT', 'BODY', 'BOIL', 'BOLD',
  'BOLT', 'BOMB', 'BOND', 'BONE', 'BOOK', 'BOOM', 'BOOT', 'BORE', 'BORN', 'BOSS',
  'BOTH', 'BOWL', 'BRAG', 'BRED', 'BREW', 'BRIM', 'BROW', 'BUCK', 'BULB', 'BULK',
  'BULL', 'BUMP', 'BURN', 'BURY', 'BUSH', 'BUSY', 'BUZZ',
  'CAFE', 'CAGE', 'CAKE', 'CALF', 'CALL', 'CALM', 'CAME', 'CAMP', 'CANE', 'CAPE',
  'CARD', 'CARE', 'CART', 'CASE', 'CASH', 'CAST', 'CAVE', 'CELL', 'CHAT', 'CHEF',
  'CHEW', 'CHIN', 'CHIP', 'CHOP', 'CITE', 'CITY', 'CLAD', 'CLAM', 'CLAP', 'CLAW',
  'CLAY', 'CLIP', 'CLOT', 'CLUB', 'CLUE', 'COAL', 'COAT', 'CODE', 'COIL', 'COIN',
  'COLD', 'COME', 'CONE', 'COOK', 'COOL', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK',
  'CORN', 'COST', 'COZY', 'CRAB', 'CRAM', 'CREW', 'CROP', 'CROW', 'CUBE', 'CUFF',
  'CURE', 'CURL', 'CUTE',
  'DAMP', 'DARE', 'DARK', 'DARN', 'DART', 'DASH', 'DATA', 'DATE', 'DAWN', 'DEAD',
  'DEAF', 'DEAL', 'DEAR', 'DEBT', 'DECK', 'DEED', 'DEEP', 'DEER', 'DESK', 'DIAL',
  'DICE', 'DIET', 'DIME', 'DINE', 'DIRE', 'DIRT', 'DISH', 'DISK', 'DIVE', 'DOCK',
  'DOES', 'DOLL', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DOSE', 'DOVE', 'DOWN', 'DRAG',
  'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUM', 'DUAL', 'DUCK', 'DUEL', 'DUET', 'DULL',
  'DULY', 'DUMB', 'DUMP', 'DUNE', 'DUNK', 'DUSK', 'DUST', 'DUTY',
  'EACH', 'EARN', 'EASE', 'EAST', 'EASY', 'ECHO', 'EDGE', 'EDIT', 'ELSE', 'ENVY',
  'EPIC', 'EVEN', 'EVER', 'EVIL', 'EXAM', 'EXIT', 'EYED',
  'FACE', 'FACT', 'FADE', 'FAIL', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FANG', 'FARE',
  'FARM', 'FAST', 'FATE', 'FEAR', 'FEAT', 'FEED', 'FEEL', 'FEET', 'FELL', 'FELT',
  'FEND', 'FERN', 'FILE', 'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH',
  'FIST', 'FIVE', 'FLAG', 'FLAP', 'FLAT', 'FLAW', 'FLEA', 'FLED', 'FLEE', 'FLEW',
  'FLEX', 'FLIP', 'FLOW', 'FOAM', 'FOIL', 'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD',
  'FOOL', 'FOOT', 'FORD', 'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR', 'FREE', 'FRET',
  'FROG', 'FROM', 'FUEL', 'FULL', 'FUME', 'FUND', 'FURY', 'FUSE', 'FUSS',
  'GAIN', 'GALA', 'GALE', 'GAME', 'GANG', 'GAPE', 'GATE', 'GAZE', 'GEAR', 'GEMS',
  'GENE', 'GERM', 'GIFT', 'GILL', 'GIRL', 'GIVE', 'GLAD', 'GLEE', 'GLOW', 'GLUE',
  'GOAL', 'GOAT', 'GOLD', 'GOLF', 'GONE', 'GOOD', 'GOWN', 'GRAB', 'GRAM', 'GRAY',
  'GREW', 'GREY', 'GRID', 'GRIM', 'GRIN', 'GRIP', 'GROW', 'GULF', 'GULL', 'GUST',
  'HAIL', 'HAIR', 'HALL', 'HALO', 'HALT', 'HAND', 'HANG', 'HARD', 'HARE', 'HARM',
  'HARP', 'HATE', 'HAVE', 'HAWK', 'HAZE', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT',
  'HEED', 'HEEL', 'HEIR', 'HELD', 'HELL', 'HELP', 'HERB', 'HERD', 'HERE', 'HERO',
  'HERS', 'HIDE', 'HIGH', 'HIKE', 'HILL', 'HINT', 'HIRE', 'HOLD', 'HOLE', 'HOME',
  'HONE', 'HOOD', 'HOOK', 'HOOP', 'HOPE', 'HORN', 'HOSE', 'HOST', 'HOUR', 'HOWL',
  'HUGE', 'HULL', 'HUNG', 'HUNT', 'HURT', 'HUSH', 'HYMN',
  'ICED', 'ICON', 'IDEA', 'IDLE', 'IDOL', 'INCH', 'INFO', 'INTO', 'IRON', 'ITCH',
  'ITEM', 'JAZZ', 'JEAN', 'JEST', 'JOIN', 'JOKE', 'JULY', 'JUMP', 'JUNE', 'JUNK',
  'JURY', 'JUST',
  'KEEN', 'KEEP', 'KEPT', 'KICK', 'KIND', 'KING', 'KISS', 'KITE', 'KNEE', 'KNEW',
  'KNIT', 'KNOB', 'KNOT', 'KNOW',
  'LACE', 'LACK', 'LADY', 'LAID', 'LAKE', 'LAMB', 'LAME', 'LAMP', 'LAND', 'LANE',
  'LARK', 'LAST', 'LATE', 'LAVA', 'LAWN', 'LAZY', 'LEAD', 'LEAF', 'LEAK', 'LEAN',
  'LEAP', 'LEFT', 'LEND', 'LENS', 'LESS', 'LEST', 'LEVY', 'LIAR', 'LICE', 'LICK',
  'LIFT', 'LIKE', 'LILY', 'LIME', 'LINE', 'LINK', 'LINT', 'LION', 'LIST', 'LIVE',
  'LOAD', 'LOAF', 'LOAN', 'LOCK', 'LOFT', 'LONE', 'LONG', 'LOOK', 'LOOP', 'LORD',
  'LOSE', 'LOSS', 'LOST', 'LOUD', 'LOVE', 'LUCK', 'LUMP', 'LUNG', 'LURE', 'LUSH',
  'MADE', 'MAID', 'MAIL', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MALT', 'MANY', 'MARE',
  'MARK', 'MARS', 'MASK', 'MASS', 'MAST', 'MATE', 'MATH', 'MAZE', 'MEAL', 'MEAN',
  'MEAT', 'MEET', 'MELT', 'MEMO', 'MEND', 'MENU', 'MERE', 'MESH', 'MESS', 'MICE',
  'MILD', 'MILE', 'MILK', 'MILL', 'MIND', 'MINE', 'MINT', 'MISS', 'MIST', 'MOAT',
  'MOCK', 'MODE', 'MOLD', 'MOLE', 'MONK', 'MOOD', 'MOON', 'MOOR', 'MORE', 'MOSS',
  'MOST', 'MOTH', 'MOVE', 'MUCH', 'MULE', 'MUST', 'MYTH',
  'NAIL', 'NAME', 'NAVY', 'NEAR', 'NEAT', 'NECK', 'NEED', 'NEST', 'NEWS', 'NEWT',
  'NEXT', 'NICE', 'NINE', 'NODE', 'NONE', 'NOON', 'NORM', 'NOSE', 'NOTE', 'NOUN',
  'NUMB',
  'OATH', 'OATS', 'OBEY', 'ODDS', 'ODOR', 'OGLE', 'OGRE', 'OILY', 'OINK', 'OKAY',
  'OMEN', 'OMIT', 'ONCE', 'ONLY', 'ONTO', 'OOZE', 'OPEN', 'ORAL', 'ORCA', 'OURS',
  'OVAL', 'OVEN', 'OVER',
  'PACE', 'PACK', 'PACT', 'PAGE', 'PAID', 'PAIL', 'PAIN', 'PAIR', 'PALE', 'PALM',
  'PANE', 'PANG', 'PANT', 'PARK', 'PART', 'PASS', 'PAST', 'PATH', 'PAVE', 'PAWN',
  'PEAK', 'PEAR', 'PEAS', 'PECK', 'PEEL', 'PEER', 'PELT', 'PERK', 'PEST', 'PICK',
  'PIER', 'PILE', 'PILL', 'PINE', 'PINK', 'PINT', 'PIPE', 'PITY', 'PLAN', 'PLAY',
  'PLEA', 'PLOD', 'PLOT', 'PLOW', 'PLOY', 'PLUG', 'PLUM', 'PLUS', 'POEM', 'POET',
  'POKE', 'POLE', 'POLL', 'POLO', 'POND', 'PONY', 'POOL', 'POOR', 'POPE', 'PORK',
  'PORT', 'POSE', 'POST', 'POUR', 'PRAY', 'PREY', 'PROP', 'PROW', 'PUFF', 'PULL',
  'PULP', 'PUMP', 'PUNK', 'PUNT', 'PUPA', 'PURE', 'PUSH',
  'QUAY', 'QUID', 'QUIP', 'QUIT', 'QUIZ',
  'RACE', 'RACK', 'RAFT', 'RAGE', 'RAID', 'RAIL', 'RAIN', 'RAKE', 'RAMP', 'RANG',
  'RANK', 'RANT', 'RARE', 'RASH', 'RATE', 'RAVE', 'RAYS', 'RAZE', 'READ', 'REAL',
  'REAM', 'REAP', 'REAR', 'REED', 'REEF', 'REEL', 'REIN', 'RELY', 'RENT', 'REST',
  'RICE', 'RICH', 'RIDE', 'RIFE', 'RIFT', 'RILE', 'RIME', 'RING', 'RINK', 'RIOT',
  'RIPE', 'RISE', 'RISK', 'RITE', 'ROAD', 'ROAM', 'ROAR', 'ROBE', 'ROCK', 'RODE',
  'ROLE', 'ROLL', 'ROOF', 'ROOM', 'ROOT', 'ROPE', 'ROSE', 'ROSY', 'ROTE', 'ROUT',
  'ROVE', 'RUDE', 'RUIN', 'RULE', 'RUNG', 'RUNT', 'RUSH', 'RUST',
  'SACK', 'SAFE', 'SAGA', 'SAGE', 'SAID', 'SAIL', 'SAKE', 'SALE', 'SALT', 'SAME',
  'SAND', 'SANE', 'SANG', 'SANK', 'SASH', 'SAVE', 'SCAN', 'SCAR', 'SEAL', 'SEAM',
  'SEAR', 'SEAS', 'SEAT', 'SEED', 'SEEK', 'SEEM', 'SEEN', 'SELF', 'SELL', 'SEND',
  'SENT', 'SERF', 'SHIP', 'SHOE', 'SHOP', 'SHOT', 'SHOW', 'SHUT', 'SICK', 'SIDE',
  'SIFT', 'SIGH', 'SIGN', 'SILK', 'SILL', 'SILO', 'SILT', 'SINE', 'SING', 'SINK',
  'SIRE', 'SITE', 'SIZE', 'SKID', 'SKIM', 'SKIN', 'SKIP', 'SKIT', 'SLAB', 'SLAM',
  'SLAP', 'SLAT', 'SLAY', 'SLED', 'SLEW', 'SLID', 'SLIM', 'SLIP', 'SLIT', 'SLOB',
  'SLOT', 'SLOW', 'SLUG', 'SLUM', 'SLUR', 'SMOG', 'SMUG', 'SNAG', 'SNAP', 'SNIP',
  'SNOB', 'SNOW', 'SNUB', 'SNUG', 'SOAK', 'SOAP', 'SOAR', 'SOCK', 'SODA', 'SOFA',
  'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOLO', 'SOME', 'SONG', 'SOON', 'SOOT', 'SORE',
  'SORT', 'SOUL', 'SOUP', 'SOUR', 'SPAN', 'SPAR', 'SPAT', 'SPIN', 'SPIT', 'SPOT',
  'SPUN', 'SPUR', 'STAB', 'STAG', 'STAR', 'STAT', 'STAY', 'STEM', 'STEP', 'STEW',
  'STIR', 'STOP', 'STOW', 'STUB', 'STUD', 'STUN', 'SUCH', 'SUIT', 'SULK', 'SUMS',
  'SUNG', 'SUNK', 'SURE', 'SURF', 'SWAM', 'SWAN', 'SWAP', 'SWAT', 'SWAY', 'SWIM',
  'TACK', 'TACO', 'TAIL', 'TAKE', 'TALE', 'TALK', 'TALL', 'TAME', 'TANK', 'TAPE',
  'TAPS', 'TARE', 'TART', 'TASK', 'TAUT', 'TAXI', 'TEAK', 'TEAL', 'TEAM', 'TEAR',
  'TEED', 'TELL', 'TEND', 'TENT', 'TERM', 'TEST', 'TEXT', 'THAN', 'THAT', 'THAW',
  'THEE', 'THEM', 'THEN', 'THEY', 'THIN', 'THIS', 'THUD', 'THUG', 'THUS', 'TICK',
  'TIDE', 'TIDY', 'TIED', 'TIER', 'TILE', 'TILL', 'TILT', 'TIME', 'TINT', 'TINY',
  'TIRE', 'TOAD', 'TOIL', 'TOLD', 'TOLL', 'TOMB', 'TONE', 'TOOK', 'TOOL', 'TOOT',
  'TORE', 'TORN', 'TOSS', 'TOTE', 'TOUR', 'TOWN', 'TRAM', 'TRAP', 'TRAY', 'TREE',
  'TREK', 'TRIM', 'TRIO', 'TRIP', 'TROD', 'TROT', 'TRUE', 'TUBA', 'TUBE', 'TUCK',
  'TUFT', 'TUNA', 'TUNE', 'TURF', 'TURN', 'TUSK', 'TWIG', 'TWIN', 'TWIT', 'TYPE',
  'UGLY', 'UNDO', 'UNIT', 'UNTO', 'UPON', 'URGE', 'USED', 'USER',
  'VAIN', 'VARY', 'VASE', 'VAST', 'VEAL', 'VEER', 'VEIL', 'VEIN', 'VENT', 'VERB',
  'VERY', 'VEST', 'VETO', 'VIAL', 'VIBE', 'VICE', 'VIEW', 'VILE', 'VINE', 'VISA',
  'VOID', 'VOLT', 'VOTE',
  'WADE', 'WAGE', 'WAIL', 'WAIT', 'WAKE', 'WALK', 'WALL', 'WAND', 'WANT', 'WARD',
  'WARM', 'WARN', 'WARP', 'WART', 'WARY', 'WASH', 'WASP', 'WAVE', 'WAVY', 'WAXY',
  'WEAK', 'WEAR', 'WEED', 'WEEK', 'WEEP', 'WELD', 'WELL', 'WELT', 'WENT', 'WEPT',
  'WERE', 'WEST', 'WHAM', 'WHAT', 'WHEN', 'WHIP', 'WHIR', 'WHOM', 'WICK', 'WIDE',
  'WIFE', 'WILD', 'WILL', 'WILT', 'WILY', 'WIND', 'WINE', 'WING', 'WINK', 'WIPE',
  'WIRE', 'WISE', 'WISH', 'WISP', 'WITH', 'WITS', 'WOKE', 'WOLF', 'WOMB', 'WOOD',
  'WOOF', 'WOOL', 'WORD', 'WORE', 'WORK', 'WORM', 'WORN', 'WOVE', 'WRAP',
  'YARD', 'YARN', 'YAWN', 'YEAR', 'YELL', 'YELP', 'YOGA', 'YOKE', 'YOLK', 'YOUR',
  'ZEAL', 'ZERO', 'ZEST', 'ZINC', 'ZONE', 'ZOOM',
  'APPLE', 'BEACH', 'BREAD', 'BRICK', 'CANDY', 'CHAIR', 'CHARM', 'CHEST', 'CHILI',
  'CHIME', 'CIVIC', 'CLAIM', 'CLAMP', 'CLANG', 'CLASH', 'CLASS', 'CLEAN', 'CLEAR',
  'CLERK', 'CLICK', 'CLIFF', 'CLIMB', 'CLOAK', 'CLOCK', 'CLONE', 'CLOSE', 'CLOTH',
  'CLOUD', 'CLOWN', 'COAST', 'COBRA', 'COCOA', 'COLON', 'COLOR', 'COMET', 'COMIC',
  'COMMA', 'CORAL', 'CORAL', 'COUNT', 'COURT', 'COVER', 'CRACK', 'CRAFT', 'CRANE',
  'CRANK', 'CRASH', 'CRATE', 'CRAVE', 'CRAWL', 'CRAZE', 'CRAZY', 'CREAM', 'CREED',
  'CREEK', 'CREEP', 'CREST', 'CRISP', 'CROOK', 'CROSS', 'CROWD', 'CROWN', 'CRUDE',
  'CRUEL', 'CRUMB', 'CRUSH', 'CRUST', 'CURVE',
  'DAILY', 'DAIRY', 'DAISY', 'DANCE', 'DANDY', 'DATED', 'DEALT', 'DEATH', 'DEBIT',
  'DEBUG', 'DEBUT', 'DECAY', 'DECOR', 'DELAY', 'DELTA', 'DELVE', 'DEMON', 'DENIM',
  'DENSE', 'DEPTH', 'DERBY', 'DIGIT', 'DIRTY', 'DISCO', 'DITCH', 'DIVER', 'DIZZY',
  'DODGE', 'DOING', 'DONOR', 'DOUBT', 'DOUGH', 'DOVER', 'DOWRY', 'DOZEN', 'DRAFT',
  'DRAIN', 'DRAKE', 'DRAMA', 'DRANK', 'DRAPE', 'DRAWN', 'DREAD', 'DREAM', 'DRESS',
  'DRIED', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DROWN',
  'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EASEL', 'EATEN', 'EDICT', 'EIGHT', 'ELBOW',
  'ELDER', 'ELECT', 'ELITE', 'EMBER', 'EMPTY', 'ENACT', 'ENDED', 'ENEMY', 'ENJOY',
  'ENTER', 'ENTRY', 'EQUAL', 'ERROR', 'ESSAY', 'ETHIC', 'EVENT', 'EVERY', 'EXACT',
  'EXCEL', 'EXILE', 'EXIST', 'EXTRA',
  'FABLE', 'FACED', 'FAINT', 'FAIRY', 'FAITH', 'FALSE', 'FANCY', 'FARCE',
  'FATAL', 'FAULT', 'FAVOR', 'FEAST', 'FENCE', 'FERRY', 'FEVER', 'FEWER', 'FIBER',
  'FIELD', 'FIEND', 'FIFTH', 'FIFTY', 'FIGHT', 'FILED', 'FINAL', 'FIRST', 'FLAME',
  'FLANK', 'FLARE', 'FLASH', 'FLASK', 'FLEET', 'FLESH', 'FLIES', 'FLING', 'FLINT',
  'FLIRT', 'FLOAT', 'FLOCK', 'FLOOD', 'FLOOR', 'FLORA', 'FLOSS', 'FLOUR', 'FLUID',
  'FLUKE', 'FLUNG', 'FLUNK', 'FLUSH', 'FLUTE', 'FOCUS', 'FOGGY', 'FORCE', 'FORGE',
  'FORGO', 'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FREAK',
  'FRESH', 'FRIED', 'FRONT', 'FROST', 'FROWN', 'FROZE', 'FRUIT', 'FUDGE', 'FULLY',
  'FUNNY',
  'GIANT', 'GIVEN', 'GLADE', 'GLAND', 'GLARE', 'GLASS', 'GLAZE', 'GLEAM', 'GLIDE',
  'GLINT', 'GLOAT', 'GLOBE', 'GLOOM', 'GLORY', 'GLOSS', 'GLOVE', 'GOING', 'GOOSE',
  'GRACE', 'GRADE', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS',
  'GRATE', 'GRAVE', 'GRAVY', 'GRAZE', 'GREAT', 'GREED', 'GREEN', 'GREET', 'GRIEF',
  'GRILL', 'GRIME', 'GRIND', 'GRIPE', 'GROAN', 'GROOM', 'GROPE', 'GROSS', 'GROUP',
  'GROVE', 'GROWL', 'GROWN', 'GRUEL', 'GRUFF', 'GRUNT', 'GUARD', 'GUESS', 'GUEST',
  'GUIDE', 'GUILD', 'GUILT', 'GUISE',
  'HABIT', 'HAIRY', 'HAPPY', 'HARDY', 'HAREM', 'HARSH', 'HASTE', 'HASTY', 'HATCH',
  'HATER', 'HAUNT', 'HAVEN', 'HAVOC', 'HAZEL', 'HEADY', 'HEARD', 'HEART', 'HEATH',
  'HEAVE', 'HEAVY', 'HEDGE', 'HEFTY', 'HEIST', 'HELIX', 'HELLO', 'HENCE', 'HERON',
  'HINGE', 'HOARD', 'HOBBY', 'HOIST', 'HONEY', 'HONOR', 'HORDE', 'HORSE', 'HOTEL',
  'HOUND', 'HOUSE', 'HOVER', 'HUMAN', 'HUMID', 'HUMOR', 'HURRY', 'HUSKY',
  'ICING', 'IDEAL', 'IDIOM', 'IDIOT', 'IMAGE', 'IMPLY', 'INBOX', 'INDEX', 'INDIE',
  'INEPT', 'INERT', 'INFER', 'INGOT', 'INKER', 'INLET', 'INNER', 'INPUT', 'INSET',
  'INTEL', 'INTRO', 'IONIC', 'IRATE', 'IRONY', 'ISSUE', 'IVORY',
  'JELLY', 'JEWEL', 'JOLLY', 'JUDGE', 'JUICE',
  'KARMA', 'KAYAK', 'KAZOO', 'KEBAB', 'KHAKI', 'KIOSK', 'KNACK', 'KNAVE', 'KNEAD',
  'KNEEL', 'KNELT', 'KNIFE', 'KNOCK', 'KNOLL', 'KNOWN', 'KOALA',
  'LABEL', 'LABOR', 'LADEN', 'LADLE', 'LAGER', 'LAIRY', 'LAMPS', 'LANCE', 'LANKY',
  'LAPEL', 'LAPSE', 'LARGE', 'LARVA', 'LASER', 'LASSO', 'LATCH', 'LATER', 'LATEX',
  'LATHE', 'LATTE', 'LAUGH', 'LAYER', 'LEACH', 'LEAFY', 'LEAKY', 'LEANT', 'LEAPT',
  'LEARN', 'LEASE', 'LEASH', 'LEAST', 'LEAVE', 'LEDGE', 'LEECH', 'LEERY', 'LEFTY',
  'LEGAL', 'LEGGY', 'LEMON', 'LEMUR', 'LEPER', 'LEVEL', 'LEVER', 'LIBEL', 'LIEGE',
  'LIGHT', 'LIKEN', 'LILAC', 'LIMBO', 'LIMIT', 'LINEN', 'LINER', 'LINGO', 'LINKS',
  'LIONS', 'LIVER', 'LIVID', 'LLAMA', 'LOAMY', 'LOATH', 'LOBBY', 'LOCAL', 'LOCUS',
  'LODGE', 'LOFTY', 'LOGIC', 'LOGIN', 'LOOSE', 'LORRY', 'LOSER', 'LOUSE', 'LOUSY',
  'LOVER', 'LOWER', 'LOWLY', 'LOYAL', 'LUCID', 'LUCKY', 'LUMEN', 'LUMPY', 'LUNAR',
  'LUNCH', 'LUNGE', 'LUPUS', 'LURCH', 'LURID', 'LYRIC',
  'MACAW', 'MACHO', 'MACRO', 'MADAM', 'MADLY', 'MAFIA', 'MAGIC', 'MAGMA', 'MAIZE',
  'MAJOR', 'MAKER', 'MANGO', 'MANIA', 'MANIC', 'MANLY', 'MANOR', 'MAPLE', 'MARCH',
  'MARRY', 'MARSH', 'MASON', 'MATCH', 'MATTE', 'MAUVE', 'MAXIM', 'MAYBE', 'MAYOR',
  'MEALY', 'MEANT', 'MEATY', 'MEDAL', 'MEDIA', 'MEDIC', 'MELON', 'MERCY', 'MERGE',
  'MERIT', 'MERRY', 'METAL', 'METER', 'METRO', 'MICRO', 'MIDST', 'MIGHT', 'MINOR',
  'MINTY', 'MINUS', 'MIRTH', 'MISER', 'MISTY', 'MIXER', 'MOCHA', 'MODAL', 'MODEL',
  'MODEM', 'MOIST', 'MOLAR', 'MOLDY', 'MONEY', 'MONTH', 'MOOSE', 'MORAL', 'MORPH',
  'MOSSY', 'MOTEL', 'MOTIF', 'MOTOR', 'MOTTO', 'MOUND', 'MOUNT', 'MOURN', 'MOUSE',
  'MOUTH', 'MOVER', 'MOVIE', 'MOWER', 'MUCUS', 'MUDDY', 'MULCH', 'MUMMY', 'MUNCH',
  'MURAL', 'MURKY', 'MUSHY', 'MUSIC', 'MUSKY', 'MUSTY',
  'NACHO', 'NAIVE', 'NANNY', 'NASAL', 'NASTY', 'NATAL', 'NAVAL', 'NAVEL', 'NEEDY',
  'NEIGH', 'NERDY', 'NERVE', 'NEVER', 'NEWER', 'NEWLY', 'NICER', 'NICHE', 'NIECE',
  'NIGHT', 'NINJA', 'NINTH', 'NOBLE', 'NOBLY', 'NOISE', 'NOISY', 'NOMAD', 'NORTH',
  'NOTCH', 'NOTED', 'NOVEL', 'NUDGE', 'NURSE', 'NUTTY', 'NYLON',
  'OASIS', 'OBESE', 'OCCUR', 'OCEAN', 'OCTET', 'ODDER', 'ODDLY', 'OFFAL', 'OFFER',
  'OFTEN', 'OLDEN', 'OLDER', 'OLIVE', 'OMEGA', 'ONION', 'ONSET', 'OPERA', 'OPINE',
  'OPIUM', 'OPTIC', 'ORBIT', 'ORDER', 'ORGAN', 'OTHER', 'OTTER', 'OUGHT', 'OUNCE',
  'OUTDO', 'OUTER', 'OUTGO', 'OVARY', 'OVATE', 'OVERT', 'OVINE', 'OVOID', 'OWING',
  'OWNER', 'OXIDE',
  'PAINT', 'PANEL', 'PANIC', 'PANSY', 'PANTS', 'PAPER', 'PARKA', 'PARRY', 'PARSE',
  'PARTY', 'PASTA', 'PASTE', 'PASTY', 'PATCH', 'PATIO', 'PATSY', 'PATTY', 'PAUSE',
  'PAYEE', 'PAYER', 'PEACE', 'PEACH', 'PEARL', 'PECAN', 'PEDAL', 'PENAL', 'PENCE',
  'PENNE', 'PENNY', 'PERCH', 'PERIL', 'PERKY', 'PESKY', 'PESTO', 'PETAL', 'PETTY',
  'PHASE', 'PHONE', 'PHONY', 'PHOTO', 'PIANO', 'PICKY', 'PIECE', 'PIETY', 'PILOT',
  'PINCH', 'PINEY', 'PINKY', 'PINTO', 'PIOUS', 'PIPER', 'PIQUE', 'PITCH', 'PITHY',
  'PIVOT', 'PIXEL', 'PIXIE', 'PIZZA', 'PLACE', 'PLAID', 'PLAIN', 'PLAIT', 'PLANE',
  'PLANK', 'PLANT', 'PLATE', 'PLAZA', 'PLEAD', 'PLEAT', 'PLIED', 'PLIER', 'PLUCK',
  'PLUMB', 'PLUME', 'PLUMP', 'PLUNK', 'PLUSH', 'POACH', 'POINT', 'POISE', 'POKER',
  'POLAR', 'POLKA', 'POLYP', 'POOCH', 'POPPY', 'PORCH', 'POSER', 'POSIT', 'POSSE',
  'POUCH', 'POUND', 'POUTY', 'POWER', 'PRANK', 'PRAWN', 'PREEN', 'PRESS', 'PRICE',
  'PRICK', 'PRIDE', 'PRIED', 'PRIME', 'PRIMO', 'PRINT', 'PRIOR', 'PRISM', 'PRIVY',
  'PRIZE', 'PROBE', 'PRONE', 'PRONG', 'PROOF', 'PROSE', 'PROUD', 'PROVE', 'PROWL',
  'PROXY', 'PRUDE', 'PRUNE', 'PSALM', 'PUDGY', 'PUFFY', 'PULPY', 'PULSE',
  'PUNCH', 'PUPIL', 'PUPPY', 'PUREE', 'PURER', 'PURGE', 'PURSE', 'PUSHY', 'PUTTY',
  'PYGMY',
  'QUACK', 'QUAIL', 'QUAKE', 'QUALM', 'QUARK', 'QUART', 'QUASH', 'QUASI', 'QUEEN',
  'QUEER', 'QUELL', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUILL', 'QUILT',
  'QUIRK', 'QUITE', 'QUOTA', 'QUOTE', 'QUOTH',
  'RABBI', 'RABID', 'RACER', 'RADAR', 'RADII', 'RADIO', 'RAINY', 'RAISE', 'RAJAH',
  'RALLY', 'RALPH', 'RAMEN', 'RANCH', 'RANDY', 'RANGE', 'RAPID', 'RARER', 'RASPY',
  'RATIO', 'RATTY', 'RAVEN', 'RAYON', 'RAZOR', 'REACH', 'REACT', 'READY', 'REALM',
  'REARM', 'REBAR', 'REBEL', 'REBUS', 'REBUT', 'RECAP', 'RECUR', 'RECUT', 'REEDY',
  'REFER', 'REFIT', 'REGAL', 'REHAB', 'REIGN', 'RELAX', 'RELAY', 'RELIC', 'REMIT',
  'RENAL', 'RENEW', 'REPAY', 'REPEL', 'REPLY', 'RERUN', 'RESET', 'RESIN', 'RETCH',
  'RETRO', 'RETRY', 'REUSE', 'REVEL', 'REVUE', 'RHINO', 'RHYME', 'RIDER', 'RIDGE',
  'RIFLE', 'RIGHT', 'RIGID', 'RIGOR', 'RINSE', 'RIPEN', 'RIPER', 'RISEN', 'RISER',
  'RISKY', 'RIVAL', 'RIVER', 'RIVET', 'ROACH', 'ROAST', 'ROBIN', 'ROBOT', 'ROCKY',
  'RODEO', 'ROGER', 'ROGUE', 'ROOMY', 'ROOST', 'ROTOR', 'ROUGE', 'ROUGH', 'ROUND',
  'ROUSE', 'ROUTE', 'ROVER', 'ROWDY', 'ROWER', 'ROYAL', 'RUDDY', 'RUDER', 'RUGBY',
  'RULER', 'RUMBA', 'RUMOR', 'RUPEE', 'RURAL', 'RUSTY',
  'SADLY', 'SAFER', 'SAINT', 'SALAD', 'SALLY', 'SALON', 'SALSA', 'SALTY', 'SALVE',
  'SALVO', 'SANDY', 'SANER', 'SAPPY', 'SASSY', 'SATIN', 'SATYR', 'SAUCE', 'SAUCY',
  'SAUNA', 'SAUTE', 'SAVOR', 'SAVOY', 'SAVVY', 'SCALD', 'SCALE', 'SCALP', 'SCALY',
  'SCAMP', 'SCANT', 'SCARE', 'SCARF', 'SCARY', 'SCENE', 'SCENT', 'SCION', 'SCOFF',
  'SCOLD', 'SCONE', 'SCOOP', 'SCOPE', 'SCORE', 'SCORN', 'SCOUR', 'SCOUT', 'SCOWL',
  'SCRAM', 'SCRAP', 'SCREE', 'SCREW', 'SCRUB', 'SCRUM', 'SCUBA', 'SEDAN', 'SEEDY',
  'SEGUE', 'SEIZE', 'SENSE', 'SEPIA', 'SERIF', 'SERUM', 'SERVE', 'SETUP', 'SEVEN',
  'SEVER', 'SEWER', 'SHACK', 'SHADE', 'SHADY', 'SHAFT', 'SHAKE', 'SHAKY', 'SHALE',
  'SHALL', 'SHALT', 'SHAME', 'SHANK', 'SHAPE', 'SHARD', 'SHARE', 'SHARK', 'SHARP',
  'SHAVE', 'SHAWL', 'SHEAR', 'SHEEN', 'SHEEP', 'SHEER', 'SHEET', 'SHEIK', 'SHELF',
  'SHELL', 'SHIED', 'SHIFT', 'SHINE', 'SHINY', 'SHIRE', 'SHIRK', 'SHIRT', 'SHOAL',
  'SHOCK', 'SHONE', 'SHOOK', 'SHOOT', 'SHORE', 'SHORN', 'SHORT', 'SHOUT', 'SHOVE',
  'SHOWN', 'SHOWY', 'SHREW', 'SHRUB', 'SHRUG', 'SHUCK', 'SHUNT', 'SHUSH', 'SHYLY',
  'SIEGE', 'SIEVE', 'SIGHT', 'SIGMA', 'SILKY', 'SILLY', 'SINCE', 'SINEW', 'SINGE',
  'SIREN', 'SISSY', 'SIXTH', 'SIXTY', 'SKATE', 'SKIER', 'SKIFF', 'SKILL', 'SKIMP',
  'SKIRT', 'SKULK', 'SKULL', 'SKUNK', 'SLACK', 'SLAIN', 'SLANG', 'SLANT', 'SLASH',
  'SLATE', 'SLAVE', 'SLEEK', 'SLEEP', 'SLEET', 'SLEPT', 'SLICE', 'SLICK', 'SLIDE',
  'SLIME', 'SLIMY', 'SLING', 'SLINK', 'SLOOP', 'SLOPE', 'SLOSH', 'SLOTH', 'SLUMP',
  'SLUNG', 'SLUNK', 'SLURP', 'SLUSH', 'SLYLY', 'SMACK', 'SMALL', 'SMART', 'SMASH',
  'SMEAR', 'SMELL', 'SMELT', 'SMILE', 'SMIRK', 'SMITE', 'SMITH', 'SMOCK', 'SMOKE',
  'SMOKY', 'SMOTE', 'SNACK', 'SNAIL', 'SNAKE', 'SNAKY', 'SNARE', 'SNARL', 'SNEAK',
  'SNEER', 'SNIDE', 'SNIFF', 'SNIPE', 'SNOOP', 'SNORE', 'SNORT', 'SNOUT', 'SNOWY',
  'SNUCK', 'SOAPY', 'SOBER', 'SOGGY', 'SOLAR', 'SOLID', 'SOLVE', 'SONAR', 'SONIC',
  'SOOTH', 'SOOTY', 'SORRY', 'SOUND', 'SOUTH', 'SOWER', 'SPACE', 'SPADE', 'SPANK',
  'SPARE', 'SPARK', 'SPASM', 'SPAWN', 'SPEAK', 'SPEAR', 'SPECK', 'SPEED', 'SPELL',
  'SPELT', 'SPEND', 'SPENT', 'SPERM', 'SPICE', 'SPICY', 'SPIED', 'SPIEL', 'SPIKE',
  'SPIKY', 'SPILL', 'SPILT', 'SPINE', 'SPINY', 'SPIRE', 'SPITE', 'SPLAT', 'SPLIT',
  'SPOIL', 'SPOKE', 'SPOOF', 'SPOOK', 'SPOOL', 'SPOON', 'SPORE', 'SPORT', 'SPOUT',
  'SPRAY', 'SPREE', 'SPRIG', 'SPUNK', 'SPURN', 'SPURT', 'SQUAD', 'SQUAT', 'SQUIB',
  'STACK', 'STAFF', 'STAGE', 'STAID', 'STAIN', 'STAIR', 'STAKE', 'STALE', 'STALK',
  'STALL', 'STAMP', 'STAND', 'STANK', 'STARE', 'STARK', 'START', 'STASH', 'STATE',
  'STAVE', 'STEAD', 'STEAK', 'STEAL', 'STEAM', 'STEED', 'STEEL', 'STEEP', 'STEER',
  'STEIN', 'STERN', 'STICK', 'STIFF', 'STILL', 'STILT', 'STING', 'STINK', 'STINT',
  'STOCK', 'STOIC', 'STOKE', 'STOLE', 'STOMP', 'STONE', 'STONY', 'STOOD', 'STOOL',
  'STOOP', 'STORE', 'STORK', 'STORM', 'STORY', 'STOUT', 'STOVE', 'STRAP', 'STRAW',
  'STRAY', 'STRIP', 'STRUT', 'STUCK', 'STUDY', 'STUFF', 'STUMP', 'STUNG', 'STUNK',
  'STUNT', 'STYLE', 'SUAVE', 'SUGAR', 'SUING', 'SUITE', 'SULKY', 'SULLY', 'SUMAC',
  'SUNNY', 'SUPER', 'SURER', 'SURGE', 'SURLY', 'SUSHI', 'SWAMI', 'SWAMP', 'SWARM',
  'SWASH', 'SWATH', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET', 'SWELL', 'SWEPT', 'SWIFT',
  'SWILL', 'SWINE', 'SWING', 'SWIRL', 'SWISH', 'SWOON', 'SWOOP', 'SWORD', 'SWORE',
  'SWORN', 'SWUNG', 'SYNOD', 'SYRUP',
  'TABBY', 'TABLE', 'TABOO', 'TACIT', 'TACKY', 'TAFFY', 'TAINT', 'TAKEN', 'TAKER',
  'TALLY', 'TALON', 'TAMER', 'TANGO', 'TANGY', 'TAPER', 'TAPIR', 'TARDY', 'TAROT',
  'TASTE', 'TASTY', 'TATTY', 'TAUNT', 'TAWNY', 'TEACH', 'TEARY', 'TEASE', 'TEDDY',
  'TEETH', 'TEMPO', 'TENET', 'TENOR', 'TENSE', 'TENTH', 'TEPEE', 'TEPID', 'TERRA',
  'TERSE', 'TESTY', 'THANK', 'THEFT', 'THEIR', 'THEME', 'THERE', 'THESE', 'THETA',
  'THICK', 'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD', 'THORN', 'THOSE', 'THREE',
  'THREW', 'THROB', 'THROW', 'THRUM', 'THUMB', 'THUMP', 'THYME', 'TIARA', 'TIBIA',
  'TIDAL', 'TIGER', 'TIGHT', 'TILDE', 'TIMER', 'TIMID', 'TIPSY', 'TITAN', 'TITHE',
  'TITLE', 'TOAST', 'TODAY', 'TODDY', 'TOKEN', 'TONAL', 'TONGA', 'TONIC', 'TOOTH',
  'TOPAZ', 'TOPIC', 'TORCH', 'TORSO', 'TORUS', 'TOTAL', 'TOTEM', 'TOUCH', 'TOUGH',
  'TOWEL', 'TOWER', 'TOXIC', 'TOXIN', 'TRACE', 'TRACK', 'TRACT', 'TRADE', 'TRAIL',
  'TRAIN', 'TRAIT', 'TRAMP', 'TRASH', 'TRAWL', 'TREAD', 'TREAT', 'TREND', 'TRIAD',
  'TRIAL', 'TRIBE', 'TRICE', 'TRICK', 'TRIED', 'TRIPE', 'TRITE', 'TROLL', 'TROOP',
  'TROPE', 'TROUT', 'TROVE', 'TRUCE', 'TRUCK', 'TRUER', 'TRULY', 'TRUMP', 'TRUNK',
  'TRUSS', 'TRUST', 'TRUTH', 'TRYST', 'TUBAL', 'TUBER', 'TULIP', 'TULLE', 'TUMOR',
  'TUNIC', 'TURBO', 'TUTOR', 'TWANG', 'TWEAK', 'TWEED', 'TWEET', 'TWICE',
  'TWINE', 'TWIRL', 'TWIST', 'TWIXT',
  'UDDER', 'ULCER', 'ULTRA', 'UMBRA', 'UNCLE', 'UNCUT', 'UNDER', 'UNDID', 'UNDUE',
  'UNFED', 'UNFIT', 'UNIFY', 'UNION', 'UNITE', 'UNITY', 'UNLIT', 'UNMET', 'UNSET',
  'UNTIE', 'UNTIL', 'UNWED', 'UNZIP', 'UPPER', 'UPSET', 'URBAN', 'URINE', 'USAGE',
  'USHER', 'USING', 'USUAL', 'USURP', 'UTILE', 'UTTER',
  'VAGUE', 'VALET', 'VALID', 'VALOR', 'VALUE', 'VALVE', 'VAPID', 'VAPOR', 'VAULT',
  'VAUNT', 'VEGAN', 'VENOM', 'VENUE', 'VERGE', 'VERSE', 'VERSO', 'VERVE', 'VICAR',
  'VIDEO', 'VIGIL', 'VIGOR', 'VILLA', 'VINYL', 'VIOLA', 'VIPER', 'VIRAL', 'VIRUS',
  'VISIT', 'VISOR', 'VISTA', 'VITAL', 'VIVID', 'VIXEN', 'VOCAL', 'VODKA', 'VOGUE',
  'VOICE', 'VOILA', 'VOMIT', 'VOTER', 'VOUCH', 'VOWEL', 'VYING',
  'WACKY', 'WAFER', 'WAGER', 'WAGON', 'WAIST', 'WAIVE', 'WALTZ', 'WARTS', 'WASTE',
  'WATCH', 'WATER', 'WAVER', 'WAXEN', 'WEARY', 'WEAVE', 'WEDGE', 'WEEDY', 'WEIGH',
  'WEIRD', 'WELCH', 'WELSH', 'WENCH', 'WHACK', 'WHALE', 'WHARF', 'WHEAT', 'WHEEL',
  'WHELP', 'WHERE', 'WHICH', 'WHIFF', 'WHILE', 'WHINE', 'WHINY', 'WHIRL', 'WHISK',
  'WHITE', 'WHOLE', 'WHOOP', 'WHOSE', 'WIDEN', 'WIDER', 'WIDOW', 'WIDTH', 'WIELD',
  'WIGHT', 'WILLY', 'WIMPY', 'WINCE', 'WINCH', 'WINDY', 'WISER', 'WISPY', 'WITCH',
  'WITTY', 'WOKEN', 'WOMAN', 'WOMEN', 'WOODY', 'WOOER', 'WOOLY', 'WOOZY', 'WORDY',
  'WORLD', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WOVEN', 'WRACK',
  'WRATH', 'WREAK', 'WRECK', 'WREST', 'WRING', 'WRIST', 'WRITE', 'WRONG', 'WROTE',
  'WRUNG', 'WRYLY',
  'YACHT', 'YEARN', 'YEAST', 'YIELD', 'YOUNG', 'YOUTH',
  'ZEBRA', 'ZESTY',
  'BANANA', 'BOTTLE', 'BRIDGE', 'BUTTON', 'CAMERA', 'CANDLE', 'CARPET', 'CARROT',
  'CASTLE', 'CATTLE', 'CELERY', 'CENTER', 'CHERRY', 'CHISEL', 'CIRCLE', 'CITIES',
  'CITRUS', 'CLOSET', 'CLOVER', 'COBALT', 'COFFEE', 'COLLAR', 'COLUMN', 'COMBAT',
  'COMEDY', 'COMICS', 'COMMON', 'COOKIE', 'COPPER', 'CORNER', 'COTTON', 'COUGAR',
  'COUNTY', 'COUPLE', 'COUSIN', 'COYOTE', 'CRADLE', 'CREAMY', 'CREATE', 'CREDIT',
  'CRICKET', 'CRIMSON', 'CRISPY', 'CRITIC', 'CRUISE', 'CRUMBS', 'CRUNCH',
  'CRYSTAL', 'CUCKOO', 'CUPPED', 'CURLED', 'CURSOR', 'CURVED', 'CUSTOM',
  'DAINTY', 'DAMAGE', 'DANCER', 'DANGER', 'DASHER', 'DAZZLE', 'DEACON', 'DEALER',
  'DEARLY', 'DEBATE', 'DEBRIS', 'DECADE', 'DECENT', 'DECIDE', 'DECKED', 'DECODE',
  'DEDUCT', 'DEFEAT', 'DEFECT', 'DEFEND', 'DEFINE', 'DEGREE', 'DELAYS', 'DELETE',
  'DEMAND', 'DEMOTE', 'DENIAL', 'DENOTE', 'DENTAL', 'DEPART', 'DEPEND', 'DEPICT',
  'DEPLOY', 'DEPORT', 'DEPOSE', 'DEPUTY', 'DERAIL', 'DERIVE', 'DESERT', 'DESIGN',
  'DESIRE', 'DESKTOP', 'DESPAIR', 'DETAIL', 'DETECT', 'DEVICE', 'DEVISE', 'DEVOID',
  'DEVOTE', 'DEVOUR', 'DIAMOND', 'DIESEL', 'DIFFER', 'DIGEST', 'DILUTE', 'DIMMED',
  'DINNER', 'DIRECT', 'DISARM', 'DISHES', 'DISMAL', 'DISOWN', 'DISPEL', 'DISTAL',
  'DOCTOR', 'DOLLAR', 'DOMAIN', 'DONATE', 'DONKEY', 'DOODLE', 'DOUBLE', 'DOUBTS',
  'DRAGON', 'DRAWER', 'DREAMY', 'DRENCH', 'DRIFTS', 'DRIVER', 'DROWSY', 'DUPLEX',
  'DURING',
  'EARTHY', 'EASILY', 'EASTER', 'ECHOED', 'EDIBLE', 'EDITOR', 'EFFECT', 'EFFORT',
  'EIGHTH', 'EITHER', 'ELAPSE', 'ELATED', 'ELBOWS', 'ELDERS', 'ELEVEN', 'ELICIT',
  'EMBARK', 'EMBLEM', 'EMBRYO', 'EMERGE', 'EMPIRE', 'EMPLOY', 'ENABLE', 'ENAMEL',
  'ENCODE', 'ENDURE', 'ENERGY', 'ENGAGE', 'ENGINE', 'ENIGMA', 'ENJOYS',
  'ENOUGH', 'ENRICH', 'ENROLL', 'ENSURE', 'ENTAIL', 'ENTIRE', 'ENTITY', 'ENTOMB',
  'ENTRAP', 'ENZYME', 'EQUALS', 'EQUATE', 'EQUINE', 'EQUITY', 'ERASED', 'EROSION',
  'ERRAND', 'ESCAPE', 'ESCORT', 'ESKIMO', 'ESSAYS', 'ESTATE', 'ETHICS', 'ETHNIC',
  'EUROPE', 'EVADED', 'EVENLY', 'EVENTS', 'EVOLVE', 'EXCEED', 'EXCEPT', 'EXCESS',
  'EXCITE', 'EXCUSE', 'EXEMPT', 'EXHALE', 'EXHORT', 'EXILED', 'EXISTS', 'EXOTIC',
  'EXPAND', 'EXPECT', 'EXPEND', 'EXPERT', 'EXPIRE', 'EXPORT', 'EXPOSE', 'EXTEND',
  'EXTENT', 'FABRIC', 'FACIAL', 'FACTOR', 'FAILED', 'FAIRLY', 'FAITHS', 'FALLEN',
  'FAMILY', 'FAMOUS', 'FARMED', 'FASTEN', 'FATHER', 'FAUCET', 'FAULTS', 'FAVORS',
  'FEARED', 'FELINE', 'FELLOW', 'FEMALE', 'FENCED', 'FERRET', 'FESTIVE', 'FIANCE',
  'FIASCO', 'FIDDLE', 'FIELDS', 'FIERCE', 'FIGHTS', 'FIGURE', 'FILING', 'FILLED',
  'FILTER', 'FINALE', 'FINDER', 'FINGER', 'FINISH', 'FIRING', 'FISHED', 'FITTED',
  'FIXING', 'FLAVOR', 'FLAWED', 'FLEDGE', 'FLIGHT', 'FLIPPED', 'FLOATS', 'FLOODS',
  'FLOORS', 'FLORAL', 'FLOWER', 'FLUENT', 'FLUFFY', 'FLURRY', 'FLYING', 'FOLDER',
  'FOLLOW', 'FORBID', 'FOREST', 'FORGET', 'FORKED', 'FORMAL', 'FORMAT', 'FORMER',
  'FOSSIL', 'FOSTER', 'FOUGHT', 'FOURTH', 'FRAMED', 'FREEZE', 'FRENCH', 'FRIDGE',
  'FRIEND', 'FRIGHT', 'FRINGE', 'FROSTY', 'FROZEN', 'FRUGAL', 'FRUITS', 'FUMBLE',
  'FUTURE',
  'GADGET', 'GALAXY', 'GALLEY', 'GALLON', 'GALLOP', 'GAMBLE', 'GARDEN', 'GARLIC',
  'GARNET', 'GATHER', 'GENDER', 'GENIUS', 'GENTLE', 'GENTLY', 'GERBIL', 'GHOSTS',
  'GIBBON', 'GIFTED', 'GINGER', 'GIRAFFE', 'GLANCE', 'GLASSY', 'GLIDER', 'GLOBAL',
  'GLOOMY', 'GLOSSY', 'GLOVES', 'GOBLIN', 'GOLDEN', 'GOPHER', 'GOSPEL', 'GOSSIP',
  'GOVERN', 'GRABBY', 'GRADER', 'GRAINY', 'GRANNY', 'GRAPES', 'GRASSY', 'GRAVEL',
  'GREASY', 'GREEDY', 'GROCERY', 'GROUND', 'GROWTH', 'GRUMPY', 'GUITAR', 'GURGLE',
  'HAMMER', 'HANDLE', 'HAPPEN', 'HARBOR', 'HARDLY', 'HASSLE', 'HATRED', 'HAVING',
  'HAZARD', 'HEADED', 'HEADER', 'HEALTH', 'HEARTH', 'HEATED', 'HEAVEN', 'HEIGHT',
  'HELMET', 'HELPER', 'HERALD', 'HEREBY', 'HEREIN', 'HERMIT', 'HEROES', 'HEROIC',
  'HIDDEN', 'HIKING', 'HINDER', 'HIPPOS', 'HOCKEY', 'HOLDER', 'HOLLOW', 'HONEST',
  'HONORS', 'HOOKED', 'HORNET', 'HORRID', 'HOSTEL', 'HOTDOG', 'HUMANE', 'HUMBLE',
  'HUNGRY', 'HUNTER', 'HURDLE', 'HURTLE', 'HYBRID',
  'IGLOOS', 'IGNORE', 'IGUANA', 'IMPACT', 'IMPAIR', 'IMPALA', 'IMPART', 'IMPOSE',
  'INCOME', 'INDEED', 'INDENT', 'INDIES', 'INDOOR', 'INDUCE', 'INFANT',
  'INFECT', 'INFORM', 'INFUSE', 'INGEST', 'INHALE', 'INJECT', 'INJURE', 'INLAND',
  'INMATE', 'INNATE', 'INSANE', 'INSECT', 'INSERT', 'INSIDE', 'INSIST', 'INSULT',
  'INSURE', 'INTACT', 'INTAKE', 'INTEND', 'INTENT', 'INTERN', 'INTUNE', 'INVADE',
  'INVENT', 'INVEST', 'INVITE', 'INVOKE', 'INWARD', 'IONIZE', 'ISLAND', 'ITSELF',
  'JACKET', 'JAGUAR', 'JARGON', 'JERSEY', 'JIGGLE', 'JINGLE', 'JOCKEY', 'JOGGLE',
  'JOSTLE', 'JOVIAL', 'JUDGED', 'JUGGLE', 'JUICES', 'JUMBLE', 'JUMPED', 'JUNGLE',
  'JUNIOR', 'KETTLE', 'KIDNAP', 'KIDNEY', 'KINDLE', 'KINDLY', 'KITTEN', 'KNIGHT',
  'KNIVES', 'KNOCKS',
  'LADDER', 'LAGOON', 'LAPTOP', 'LARGER', 'LASTED', 'LATELY', 'LAUNCH', 'LAWYER',
  'LEADER', 'LEAGUE', 'LEARNED', 'LEAVES', 'LECTOR', 'LEDGER', 'LEGACY', 'LEGEND',
  'LEGION', 'LEMONS', 'LENGTH', 'LESSON', 'LETTER', 'LIABLE', 'LIFTED', 'LIKELY',
  'LIMITS', 'LINEAR', 'LINENS', 'LINGER', 'LIQUID', 'LISTEN', 'LITTLE', 'LIVELY',
  'LIVING', 'LIZARD', 'LOADED', 'LOCKER', 'LOCUST', 'LODGER', 'LONELY', 'LOUNGE',
  'LOVELY', 'LUMBER', 'LUXURY',
  'MAGNET', 'MAIDEN', 'MOSTLY', 'MOTHER', 'MOTION', 'MOTIVE', 'MOVING', 'MUMBLE',
  'MURMUR', 'MUSCLE', 'MUSEUM', 'MUTTER', 'MYSELF',
  'NAPKIN', 'NARROW', 'NATION', 'NATIVE', 'NATURE', 'NEARBY', 'NEARLY', 'NEATLY',
  'NECTAR', 'NEEDLE', 'NEGATE', 'NELSON', 'NEPHEW', 'NERVES', 'NESTLE', 'NETTLE',
  'NEURAL', 'NEURON', 'NICKEL', 'NIGHTS', 'NIMBLE', 'NINETY', 'NOBODY', 'NODDED',
  'NOODLE', 'NORMAL', 'NOTICE', 'NOTIFY', 'NOTION', 'NOUGAT', 'NOVICE', 'NUDGED',
  'NUMBER', 'NURSED', 'NUTMEG',
  'OBJECT', 'OBTAIN', 'OCCUPY', 'OCCURS', 'OCEANS', 'OCTANE', 'OCTAVE', 'OCULAR',
  'ODDEST', 'OFFEND', 'OFFICE', 'OFFSET', 'OLDEST', 'OLIVES', 'ONIONS',
  'ONLINE', 'ONWARD', 'OPAQUE', 'OPENED', 'OPENLY', 'OPERAS', 'OPPOSE', 'OPTICS',
  'OPTION', 'ORACLE', 'ORANGE', 'ORBITS', 'ORCHID', 'ORDEAL', 'ORDERS', 'ORGANS',
  'ORIGIN', 'ORIOLE', 'ORNATE', 'ORPHAN', 'OSCARS', 'OTHERS', 'OUNCES', 'OUTAGE',
  'OUTBID', 'OUTCRY', 'OUTFIT', 'OUTING', 'OUTLAW', 'OUTLAY', 'OUTLET', 'OUTPUT',
  'OUTRUN', 'OUTSET', 'OUTWIT', 'OVERDO', 'OVERLY', 'OWNERS', 'OXFORD', 'OYSTER',
  'PACIFY', 'PACKED', 'PACKET', 'PADDLE', 'PAELLA', 'PAGING', 'PAINED', 'PAINTS',
  'PALACE', 'PALATE', 'PALLID', 'PALMED', 'PAMPER', 'PANAMA', 'PANDAS', 'PANDER',
  'PANELS', 'PANICS', 'PANTRY', 'PAPAYA', 'PARADE', 'PARCEL', 'PARDON', 'PARENT',
  'PARISH', 'PARITY', 'PARKED', 'PARLOR', 'PARODY', 'PARROT', 'PARSEC', 'PARSON',
  'PARTED', 'PARTLY', 'PASSED', 'PASSER', 'PASTEL', 'PASTOR', 'PASTRY', 'PATCHY',
  'PATENT', 'PATHOS', 'PATROL', 'PATRON', 'PEACHY', 'PEBBLE', 'PECANS', 'PEDALS',
  'PEEKED', 'PEELED', 'PEEPED', 'PEERED', 'PELLET', 'PENCIL', 'PEOPLE', 'PEPPER',
  'PEPTIC', 'PERIOD', 'PERISH', 'PERMIT', 'PERSON', 'PETALS', 'PEWTER', 'PHASES',
  'PHONES', 'PHOTOS', 'PHRASE', 'PICKED', 'PICKET', 'PICKLE', 'PICNIC', 'PIECES',
  'PIERCE', 'PIGEON', 'PIGLET', 'PILLAR', 'PILLOW', 'PILOTS', 'PIMPLE', 'PINNED',
  'PIPING', 'PIRATE', 'PISTOL', 'PISTON', 'PITCHY', 'PIVOTS', 'PIXELS', 'PIZZAS',
  'PLACED', 'PLACES', 'PLAINS', 'PLANET', 'PLANTS', 'PLAQUE', 'PLASMA', 'PLATED',
  'PLATES', 'PLAYED', 'PLAYER', 'PLEASE', 'PLEDGE', 'PLENTY', 'PLIERS', 'PLIGHT',
  'PLOUGH', 'PLOWED', 'PLUCKY', 'PLUGIN', 'PLUNGE', 'PLURAL', 'POCKET', 'PODIUM',
  'POETIC', 'POETRY', 'POINTS', 'POISED', 'POISON', 'POLICE', 'POLICY', 'POLISH',
  'POLITE', 'POLLEN', 'POMMEL', 'PONCHO', 'PONIES', 'POODLE', 'POOLED', 'POORLY',
  'POPLAR', 'POPPED', 'POROUS', 'PORTAL', 'PORTED', 'PORTER', 'PORTLY', 'POSEUR',
  'POSIES', 'POSING', 'POSSUM', 'POSTAL', 'POSTED', 'POSTER', 'POTATO', 'POTENT',
  'POTION', 'POTTED', 'POUNCE', 'POUNDS', 'POURED', 'POWDER', 'POWERS', 'PRAISE',
  'PRANCE', 'PRAYED', 'PRAYER', 'PREACH', 'PREFER', 'PREFIX', 'PRESET',
  'PRESTO', 'PRETTY', 'PREYED', 'PRICED', 'PRICES', 'PRICKY', 'PRIDED', 'PRIEST',
  'PRIMAL', 'PRIMER', 'PRINCE', 'PRINTS', 'PRISON', 'PRIZED', 'PRIZES', 'PROBED',
  'PROFIT', 'PROMPT', 'PRONGS', 'PROOFS', 'PROPEL', 'PROPER', 'PROTON', 'PROVED',
  'PROVEN', 'PRUNED', 'PRUNES', 'PUBLIC', 'PUCKER', 'PUDDLE', 'PUFFED', 'PULLED',
  'PULLEY', 'PULPIT', 'PULSED', 'PUMICE', 'PUMMEL', 'PUMPED', 'PUNCHY', 'PUNDIT',
  'PUNISH', 'PUNTER', 'PUPILS', 'PUPPET', 'PURELY', 'PURGED', 'PURIFY', 'PURITY',
  'PURPLE', 'PURSUE', 'PUSHED', 'PUTRID', 'PUZZLE',
  'PYTHON', 'QUARTZ', 'QUENCH', 'QUEUED', 'QUICHE', 'QUILTS', 'QUINCE', 'QUIVER',
  'QUOTAS', 'QUOTED', 'QUOTES',
  'RABBIT', 'RABBLE', 'RACING', 'RACISM', 'RACIST', 'RACKET', 'RADARS', 'RADIAL',
  'RADIOS', 'RADISH', 'RADIUS', 'RAFFLE', 'RAFTER', 'RAGGED', 'RAGING', 'RAIDED',
  'RAIDER', 'RAILED', 'RAISIN', 'RAKISH', 'RAMBLE', 'RAMMED', 'RANCID', 'RANDOM',
  'RANGED', 'RANGER', 'RANKED', 'RANSOM', 'RAPIDS', 'RARELY', 'RARITY', 'RASCAL',
  'RASHES', 'RASTER', 'RATHER', 'RATIFY', 'RATING', 'RATION', 'RATTLE', 'RAVAGE',
  'RAVINE', 'RAVING', 'RAVISH', 'RAZORS', 'REACTS', 'READER', 'REALLY', 'REALTY',
  'REASON', 'REBATE', 'REBOOT', 'REBORN', 'REBUFF', 'REBUKE', 'RECALL', 'RECANT',
  'RECAST', 'RECEDE', 'RECENT', 'RECESS', 'RECIPE', 'RECITE', 'RECKON', 'RECOIL',
  'RECORD', 'RECTIFY', 'RECTOR', 'RECUES', 'REDACT', 'REDEEM', 'REDOES', 'REDUCE',
  'REEFED', 'REEKED', 'REELED', 'REFERS', 'REFILL', 'REFINE', 'REFLEX', 'REFORM',
  'REFUEL', 'REFUGE', 'REFUND', 'REFUSE', 'REFUTE', 'REGAIN', 'REGALE', 'REGARD',
  'REGENT', 'REGGAE', 'REGIME', 'REGION', 'REGRET', 'REHASH', 'REHEAT', 'REIGNS',
  'REJECT', 'REJOIN', 'RELATE', 'RELAYS', 'RELENT', 'RELICS', 'RELIEF', 'RELIED',
  'RELISH', 'RELIVE', 'RELOAD', 'REMAIN', 'REMAKE', 'REMAND', 'REMARK', 'REMEDY',
  'REMIND', 'REMISS', 'REMOTE', 'REMOVE', 'RENAME', 'RENDER', 'RENEGE', 'RENEWS',
  'RENOWN', 'RENTAL', 'RENTED', 'REOPEN', 'REPAID', 'REPAIR', 'REPASS', 'REPAST',
  'REPAYS', 'REPEAL', 'REPEAT', 'REPELS', 'REPENT', 'REPLAY', 'REPORT', 'REPOSE',
  'REPUTE', 'REREAD', 'REROUTE', 'RESCUE', 'RESELL', 'RESENT', 'RESIDE', 'RESIGN',
  'RESIST', 'RESITS', 'RESORT', 'RESTED', 'RESULT', 'RESUME', 'RETAIL', 'RETAIN',
  'RETAKE', 'RETARD', 'RETELL', 'RETEST', 'RETINA', 'RETIRE', 'RETOLD', 'RETOOL',
  'RETORT', 'RETOOK', 'RETORE', 'RETRACE', 'RETRACT', 'RETREAT', 'RETURN',
  'RETYPE', 'REVEAL', 'REVELS', 'REVERE', 'REVERT', 'REVIEW', 'REVISE', 'REVIVE',
  'REVOKE', 'REVOLT', 'REWARD', 'REWIND', 'REWIRE', 'REWORK', 'RHINOS', 'RHYMED',
  'RHYMES', 'RHYTHM', 'RIBBON', 'RICHER', 'RICHES', 'RICHLY', 'RIDDEN', 'RIDDLE',
  'RIDERS', 'RIDGES', 'RIDING', 'RIFFLE', 'RIFLED', 'RIFLES', 'RIGHTS', 'RILING',
  'RIMMED', 'RINGED', 'RINSED', 'RIOTER', 'RIPPED', 'RIPPLE', 'RISING', 'RISKED',
  'RITUAL', 'RIVALS', 'RIVERS', 'ROARED', 'ROASTS', 'ROBBED', 'ROBBER', 'ROBINS',
  'ROBOTS', 'ROBUST', 'ROCKET', 'RODENT', 'RODEOS', 'ROGUES', 'ROLLER', 'ROMANS',
  'ROOFED', 'ROOKIE', 'ROOMED', 'ROOSTS', 'ROOTED', 'ROPERS', 'ROPING', 'ROSARY',
  'ROSIER', 'ROSTER', 'ROTARY', 'ROTATE', 'ROTTED', 'ROTTEN', 'ROTUND', 'ROUNDS',
  'ROUSED', 'ROUTED', 'ROUTER', 'ROUTES', 'ROVING', 'ROWING', 'RUBBED', 'RUBBER',
  'RUBBLE', 'RUBIES', 'RUBRIC', 'RUDDER', 'RUDELY', 'RUEFUL', 'RUFFLE', 'RUGGED',
  'RUINED', 'RULERS', 'RULING', 'RUMBLE', 'RUMORS', 'RUMPLE', 'RUNNER', 'RUNOFF',
  'RUNWAY', 'RUSHED', 'RUSTED', 'RUSTIC', 'RUSTLE',
];

export const WAVE_LEXICON: readonly string[] = [...new Set([...THEME_WORDS, ...BONUS_EXTRA])];

const LETTERS = 'EEEEAAAIIIIOOONNNRRRTTTSSSLLLLCCCCDDDHHUUMMPPGGYYWWFFBBVKJXQZ';

export type SurvivorMove = {
  letter: string;
  from: Cell;
  to: Cell;
};

export type SpawnDrop = {
  letter: string;
  col: number;
  fromRow: number;
  to: Cell;
};

export type WavePlan = {
  grid: string[][];
  words: string[];
  theme: string;
  maskAllHints?: boolean;
  survivors: SurvivorMove[];
  spawns: SpawnDrop[];
  used: Cell[];
};

function cloneGrid(grid: string[][]): string[][] {
  return grid.map((row) => row.slice());
}

function usedSet(used: Iterable<Cell>): Set<string> {
  const set = new Set<string>();
  for (const cell of used) set.add(cellKey(cell));
  return set;
}

/** Compact unused letters down each column. Empty cells are ''. */
export function compactColumns(
  grid: string[][],
  used: Iterable<Cell>,
): { compact: string[][]; survivors: SurvivorMove[] } {
  const size = grid.length;
  const gone = usedSet(used);
  const compact = Array.from({ length: size }, () => Array.from({ length: size }, () => ''));
  const survivors: SurvivorMove[] = [];

  for (let col = 0; col < size; col++) {
    const keep: { letter: string; fromRow: number }[] = [];
    for (let row = 0; row < size; row++) {
      if (gone.has(cellKey({ row, col }))) continue;
      keep.push({ letter: grid[row]![col]!, fromRow: row });
    }
    const startRow = size - keep.length;
    keep.forEach((item, i) => {
      const toRow = startRow + i;
      compact[toRow]![col] = item.letter;
      survivors.push({
        letter: item.letter,
        from: { row: item.fromRow, col },
        to: { row: toRow, col },
      });
    });
  }
  return { compact, survivors };
}

function randInt(n: number): number {
  return Math.floor(Math.random() * n);
}

function shuffle<T>(items: readonly T[]): T[] {
  const out = items.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = randInt(i + 1);
    const tmp = out[i]!;
    out[i] = out[j]!;
    out[j] = tmp;
  }
  return out;
}

function randomLetter(): string {
  return LETTERS[randInt(LETTERS.length)]!;
}

/** One word sits inside another (TRAIN ⊃ RAIN). Same line would share a swipe. */
function nestedWords(a: string, b: string): boolean {
  return a !== b && (a.includes(b) || b.includes(a));
}

function placementCells(p: Placement): Cell[] {
  const out: Cell[] = [];
  for (let i = 0; i <= p.steps; i++) {
    out.push({ row: p.head.row + p.step.row * i, col: p.head.col + p.step.col * i });
  }
  return out;
}

function fits(grid: string[][], word: string, start: Cell, dir: Cell): boolean {
  const size = grid.length;
  for (let i = 0; i < word.length; i++) {
    const cell = { row: start.row + dir.row * i, col: start.col + dir.col * i };
    if (!inBounds(cell, size)) return false;
    const cur = grid[cell.row]![cell.col]!;
    if (cur !== '' && cur !== word[i]) return false;
  }
  return true;
}

function writeWord(grid: string[][], word: string, start: Cell, dir: Cell): void {
  for (let i = 0; i < word.length; i++) {
    grid[start.row + dir.row * i]![start.col + dir.col * i] = word[i]!;
  }
}

type Fit = { start: Cell; dir: Cell; locked: number };

function scoreFit(grid: string[][], word: string, start: Cell, dir: Cell): number {
  let locked = 0;
  for (let i = 0; i < word.length; i++) {
    const cur = grid[start.row + dir.row * i]![start.col + dir.col * i]!;
    if (cur !== '') locked += 1;
  }
  return locked;
}

function cellsOfWrite(word: string, start: Cell, dir: Cell): Cell[] {
  const out: Cell[] = [];
  for (let i = 0; i < word.length; i++) {
    out.push({ row: start.row + dir.row * i, col: start.col + dir.col * i });
  }
  return out;
}

function collectFits(grid: string[][], word: string, taken?: Set<string>): Fit[] {
  const size = grid.length;
  const out: Fit[] = [];
  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      for (const dir of DIRS) {
        const start = { row, col };
        if (!fits(grid, word, start, dir)) continue;
        const cells = cellsOfWrite(word, start, dir);
        if (taken && cells.some((c) => taken.has(cellKey(c)))) continue;
        out.push({ start, dir, locked: scoreFit(grid, word, start, dir) });
      }
    }
  }
  return out;
}

type Axis = 'h' | 'v' | 'd';

function axisOf(dir: Cell): Axis {
  if (dir.row !== 0 && dir.col !== 0) return 'd';
  return dir.row === 0 ? 'h' : 'v';
}

/** ≥1 horizontal, vertical, and diagonal when count ≥ 3. Extra slots balance the three. */
function axisQuota(count: number): Record<Axis, number> {
  const q: Record<Axis, number> = { h: 0, v: 0, d: 0 };
  if (count < 3) {
    q.h = count;
    return q;
  }
  q.h = 1;
  q.v = 1;
  q.d = 1;
  const order = shuffle<Axis>(['h', 'v', 'd']);
  for (let i = 0; i < count - 3; i++) q[order[i % 3]!] += 1;
  return q;
}

function pickFit(fitsList: Fit[], wantLocked: boolean, axis?: Axis): Fit | null {
  if (fitsList.length === 0) return null;
  let pool = wantLocked ? fitsList.filter((f) => f.locked > 0) : fitsList.slice();
  if (axis) pool = pool.filter((f) => axisOf(f.dir) === axis);
  if (pool.length === 0) return null;
  pool.sort((a, b) => b.locked - a.locked);
  const best = pool[0]!.locked;
  const top = pool.filter((f) => f.locked === best);
  return top[randInt(top.length)]!;
}

/** Force a word through a leftover letter so nails get used. */
function tryPlaceThrough(
  grid: string[][],
  cell: Cell,
  planted: string[],
  source: readonly string[],
): boolean {
  const ch = grid[cell.row]![cell.col]!;
  if (ch === '') return false;
  for (const word of shuffle(source)) {
    if (planted.includes(word) || planted.some((w) => nestedWords(w, word))) continue;
    for (let i = 0; i < word.length; i++) {
      if (word[i] !== ch) continue;
      for (const dir of shuffle(DIRS)) {
        const start = { row: cell.row - dir.row * i, col: cell.col - dir.col * i };
        if (!fits(grid, word, start, dir)) continue;
        writeWord(grid, word, start, dir);
        planted.push(word);
        return true;
      }
    }
  }
  return false;
}

function fillEmpties(grid: string[][]): Cell[] {
  const filled: Cell[] = [];
  for (let row = 0; row < grid.length; row++) {
    for (let col = 0; col < grid.length; col++) {
      if (grid[row]![col] !== '') continue;
      grid[row]![col] = randomLetter();
      filled.push({ row, col });
    }
  }
  return filled;
}

function pickWaveWords(grid: string[][], planted: string[], want: number): string[] {
  const unique = [...new Set(planted)];
  const placements = locatePlacements(grid, unique);
  const byWord = new Map<string, Placement[]>();
  for (const p of placements) {
    const list = byWord.get(p.word) ?? [];
    list.push(p);
    byWord.set(p.word, list);
  }
  const found = unique.filter((w) => (byWord.get(w)?.length ?? 0) > 0);
  found.sort((a, b) => (want >= 5 ? a.length - b.length : b.length - a.length));
  const chosen: string[] = [];
  const taken = new Set<string>();
  const have: Record<Axis, number> = { h: 0, v: 0, d: 0 };
  const quota = axisQuota(want);

  const take = (axis?: Axis): void => {
    for (const word of found) {
      if (chosen.length >= want) return;
      if (axis && have[axis] >= quota[axis]) return;
      if (chosen.includes(word) || chosen.some((w) => nestedWords(w, word))) continue;
      const free = byWord.get(word)!.filter((p) =>
        placementCells(p).every((cell) => !taken.has(cellKey(cell))),
      );
      const place = axis ? free.find((p) => axisOf(p.step) === axis) : free[0];
      if (!place) continue;
      chosen.push(word);
      have[axisOf(place.step)] += 1;
      for (const cell of placementCells(place)) taken.add(cellKey(cell));
    }
  };

  for (const axis of shuffle<Axis>(['h', 'v', 'd'])) take(axis);
  take();
  return chosen;
}

function leftoverCells(base: string[][]): Cell[] {
  const out: Cell[] = [];
  for (let row = 0; row < base.length; row++) {
    for (let col = 0; col < base.length; col++) {
      if (base[row]![col]) out.push({ row, col });
    }
  }
  return out;
}

function markNails(base: string[][], word: string, start: Cell, dir: Cell, into: Set<string>): void {
  for (let i = 0; i < word.length; i++) {
    const cell = { row: start.row + dir.row * i, col: start.col + dir.col * i };
    if (base[cell.row]?.[cell.col]) into.add(cellKey(cell));
  }
}

function plantPool(count: number, source: readonly string[]): string[] {
  const short = source.filter((w) => w.length <= 4);
  const long = source.filter((w) => w.length > 4);
  if (count >= 5) return [...shuffle(short), ...shuffle(long)];
  return shuffle(source);
}

function pickTheme(avoid?: string): WordTheme {
  const pool = WAVE_THEMES.filter((t) => t.title !== avoid);
  const list = pool.length > 0 ? pool : WAVE_THEMES;
  return list[randInt(list.length)]!;
}

function plantWords(
  base: string[][],
  count: number,
  source: readonly string[],
  opts: { requireAxes?: boolean; minCount?: number } = {},
): { grid: string[][]; words: string[] } | null {
  const grid = cloneGrid(base);
  const planted: string[] = [];
  const nails = leftoverCells(base);
  const usedNails = new Set<string>();
  const taken = new Set<string>();
  const pool = plantPool(count, source);
  const quota = axisQuota(count);
  const have: Record<Axis, number> = { h: 0, v: 0, d: 0 };

  const tryAxis = (axis: Axis | undefined, preferLocked: boolean): void => {
    for (const word of pool) {
      if (planted.length >= count) return;
      if (axis && have[axis] >= quota[axis]) return;
      if (planted.includes(word) || planted.some((w) => nestedWords(w, word))) continue;
      const fit = pickFit(collectFits(grid, word, taken), preferLocked, axis);
      if (!fit) continue;
      writeWord(grid, word, fit.start, fit.dir);
      for (const c of cellsOfWrite(word, fit.start, fit.dir)) taken.add(cellKey(c));
      markNails(base, word, fit.start, fit.dir, usedNails);
      planted.push(word);
      have[axisOf(fit.dir)] += 1;
    }
  };

  const fillAxes = (preferLocked: boolean): void => {
    for (const axis of shuffle<Axis>(['h', 'v', 'd'])) tryAxis(axis, preferLocked);
    tryAxis(undefined, preferLocked);
  };

  if (nails.length > 0) {
    fillAxes(true);
    for (const nail of shuffle(nails)) {
      if (planted.length >= count) break;
      if (usedNails.has(cellKey(nail))) continue;
      const before = planted.length;
      tryPlaceThrough(grid, nail, planted, source);
      if (planted.length > before) {
        const word = planted[planted.length - 1]!;
        for (const p of locatePlacements(grid, [word])) {
          markNails(base, word, p.head, p.step, usedNails);
          for (const c of placementCells(p)) taken.add(cellKey(c));
        }
      }
    }
  }

  fillAxes(false);

  const minCount = opts.minCount ?? count;
  if (planted.length < minCount) return null;
  fillEmpties(grid);
  const words = pickWaveWords(grid, planted, count);
  if (words.length < minCount) return null;
  if ((opts.requireAxes ?? true) && words.length >= 3 && !hasAllAxes(grid, words)) return null;
  return { grid, words };
}

function hasAllAxes(grid: string[][], words: string[]): boolean {
  const seen: Record<Axis, boolean> = { h: false, v: false, d: false };
  for (const p of locatePlacements(grid, words)) seen[axisOf(p.step)] = true;
  return seen.h && seen.v && seen.d;
}

export function createWaveLevel(size = 6, wave = 1): {
  id: number;
  theme: string;
  size: number;
  grid: string[][];
  words: string[];
} {
  const want = targetWordCount(wave);
  const theme = pickTheme();
  for (let attempt = 0; attempt < 48; attempt++) {
    const planted = plantWords(emptyGrid(size), want, theme.words);
    if (!planted) continue;
    return {
      id: 1,
      theme: theme.title,
      size,
      grid: planted.grid,
      words: planted.words,
    };
  }
  throw new Error('wave: could not seed an opening board');
}

function emptyGrid(size: number): string[][] {
  return Array.from({ length: size }, () => Array.from({ length: size }, () => ''));
}

function spawnsFrom(compact: string[][], filled: string[][]): SpawnDrop[] {
  const size = filled.length;
  const spawns: SpawnDrop[] = [];
  for (let col = 0; col < size; col++) {
    const holes: number[] = [];
    for (let row = 0; row < size; row++) {
      if (compact[row]![col] === '') holes.push(row);
    }
    holes.forEach((toRow, i) => {
      const fromRow = -holes.length + i;
      spawns.push({
        letter: filled[toRow]![col]!,
        col,
        fromRow,
        to: { row: toRow, col },
      });
    });
  }
  return spawns;
}

/**
 * Next board keeps unused letters. Only holes spawn from the top.
 * Never treat leftover nails as cleared (that made every letter fall again).
 */
export function planNextWave(
  grid: string[][],
  used: Iterable<Cell>,
  wave = 1,
  avoidTheme?: string,
  seenThemes: readonly string[] = [],
): WavePlan {
  const usedCells = [...used];
  const { compact, survivors } = compactColumns(grid, usedCells);
  const targetCount = targetWordCount(wave);
  const seen = new Set(seenThemes);
  const unused = shuffle(WAVE_THEMES.filter((t) => !seen.has(t.title) && t.title !== avoidTheme));
  const repeats = shuffle(WAVE_THEMES.filter((t) => seen.has(t.title) && t.title !== avoidTheme));
  const fallback = WAVE_THEMES.filter((t) => t.title === avoidTheme);

  const finish = (
    planted: { grid: string[][]; words: string[] },
    title: string,
    maskAllHints: boolean,
  ): WavePlan => ({
    grid: planted.grid,
    words: planted.words,
    theme: title,
    maskAllHints,
    survivors,
    spawns: spawnsFrom(compact, planted.grid),
    used: usedCells,
  });

  const tryGroup = (
    themes: readonly WordTheme[],
    count: number,
    maskAll: boolean,
    opts?: { requireAxes?: boolean; minCount?: number },
    attempts = 10,
  ): WavePlan | null => {
    for (const theme of themes) {
      for (let i = 0; i < attempts; i++) {
        const planted = plantWords(compact, count, theme.words, opts);
        if (planted) return finish(planted, theme.title, maskAll);
      }
    }
    return null;
  };

  const fresh =
    tryGroup(unused, targetCount, false) ??
    tryGroup(unused, targetCount, false, {
      requireAxes: false,
      minCount: Math.max(WAVE_MIN_WORDS, targetCount - 1),
    }, 8) ??
    tryGroup(unused, targetCount, false, { requireAxes: false, minCount: WAVE_MIN_WORDS }, 1);

  if (fresh) return fresh;

  const again =
    tryGroup(repeats, 6, true) ??
    tryGroup(repeats, 6, true, { requireAxes: false, minCount: 5 }, 8) ??
    tryGroup(repeats, 6, true, { requireAxes: false, minCount: WAVE_MIN_WORDS }, 1) ??
    tryGroup(fallback, 6, true, { requireAxes: false, minCount: WAVE_MIN_WORDS }, 8);

  if (again) return again;
  throw new Error('wave: could not seed a playable board on leftovers');
}

export function cellsFromFound(
  found: ReadonlyArray<{ start: Cell; end: Cell }>,
  cellsOnSegment: (start: Cell, end: Cell) => Cell[],
): Cell[] {
  const seen = new Set<string>();
  const out: Cell[] = [];
  for (const item of found) {
    for (const cell of cellsOnSegment(item.start, item.end)) {
      const key = cellKey(cell);
      if (seen.has(key)) continue;
      seen.add(key);
      out.push(cell);
    }
  }
  return out;
}

/** TripleMatch-style lock: book the next cell; release source after this fraction of a cell. */
export const OWNERSHIP_TRANSFER = 0.22;
export const FALL_MS_PER_CELL = 65;

export type DropCell = {
  current: number | null;
  incoming: number | null;
};

export type DropPiece = {
  id: number;
  letter: string;
  col: number;
  homeRow: number;
  originRow: number;
  visualRow: number;
  logicalRow: number;
  targetRow: number;
  dropStartRow: number;
  dropping: boolean;
};

export type SpawnQueued = {
  letter: string;
  homeRow: number;
};

export type DropSim = {
  size: number;
  cells: DropCell[][];
  pieces: DropPiece[];
  queues: SpawnQueued[][];
  nextId: number;
};

function canReceive(sim: DropSim, row: number, col: number): boolean {
  if (row < 0 || row >= sim.size || col < 0 || col >= sim.size) return false;
  const cell = sim.cells[row]![col]!;
  return cell.current === null && cell.incoming === null;
}

function pieceById(sim: DropSim, id: number): DropPiece | undefined {
  return sim.pieces.find((p) => p.id === id);
}

function startDrop(sim: DropSim, piece: DropPiece, toRow: number): boolean {
  if (!canReceive(sim, toRow, piece.col)) return false;
  sim.cells[toRow]![piece.col]!.incoming = piece.id;
  piece.targetRow = toRow;
  piece.dropStartRow = piece.visualRow;
  piece.dropping = true;
  return true;
}

/**
 * Survivors sit on their current cells. New letters queue per column,
 * deepest destination first so the first to enter lands lowest.
 */
export function beginDropSim(
  size: number,
  survivors: readonly SurvivorMove[],
  spawns: readonly SpawnDrop[],
): DropSim {
  const cells: DropCell[][] = Array.from({ length: size }, () =>
    Array.from({ length: size }, () => ({ current: null, incoming: null })),
  );
  const pieces: DropPiece[] = [];
  let nextId = 0;
  for (const s of survivors) {
    const id = nextId++;
    pieces.push({
      id,
      letter: s.letter,
      col: s.from.col,
      homeRow: s.to.row,
      originRow: s.from.row,
      visualRow: s.from.row,
      logicalRow: s.from.row,
      targetRow: s.from.row,
      dropStartRow: s.from.row,
      dropping: false,
    });
    cells[s.from.row]![s.from.col]!.current = id;
  }
  const queues: SpawnQueued[][] = Array.from({ length: size }, () => []);
  const byCol = new Map<number, SpawnDrop[]>();
  for (const s of spawns) {
    const list = byCol.get(s.col) ?? [];
    list.push(s);
    byCol.set(s.col, list);
  }
  for (const [col, list] of byCol) {
    list.sort((a, b) => b.to.row - a.to.row);
    queues[col] = list.map((s) => ({ letter: s.letter, homeRow: s.to.row }));
  }
  return { size, cells, pieces, queues, nextId };
}

function scanDrops(sim: DropSim): void {
  for (let row = 0; row < sim.size - 1; row++) {
    for (let col = 0; col < sim.size; col++) {
      const id = sim.cells[row]![col]!.current;
      if (id === null) continue;
      const piece = pieceById(sim, id);
      if (!piece || piece.dropping) continue;
      if (canReceive(sim, row + 1, col)) startDrop(sim, piece, row + 1);
    }
  }
}

function spawnAtTop(sim: DropSim): void {
  for (let col = 0; col < sim.size; col++) {
    const queue = sim.queues[col]!;
    if (queue.length === 0) continue;
    if (!canReceive(sim, 0, col)) continue;
    const next = queue.shift()!;
    const id = sim.nextId++;
    sim.pieces.push({
      id,
      letter: next.letter,
      col,
      homeRow: next.homeRow,
      originRow: -1,
      visualRow: -1,
      logicalRow: -1,
      targetRow: 0,
      dropStartRow: -1,
      dropping: true,
    });
    sim.cells[0]![col]!.incoming = id;
  }
}

function releaseOtherCells(sim: DropSim, piece: DropPiece, keepRow: number): void {
  for (let row = 0; row < sim.size; row++) {
    if (row === keepRow) continue;
    const cell = sim.cells[row]![piece.col]!;
    if (cell.current === piece.id) cell.current = null;
    if (cell.incoming === piece.id) cell.incoming = null;
  }
}

function transferOwnership(sim: DropSim, piece: DropPiece): void {
  if (!piece.dropping || piece.logicalRow === piece.targetRow) return;
  if (piece.visualRow - piece.dropStartRow < OWNERSHIP_TRANSFER) return;
  releaseOtherCells(sim, piece, piece.targetRow);
  const dst = sim.cells[piece.targetRow]![piece.col]!;
  if (dst.incoming === piece.id || dst.current === null) {
    dst.incoming = null;
    dst.current = piece.id;
  }
  piece.logicalRow = piece.targetRow;
}

function confirmAt(sim: DropSim, piece: DropPiece, row: number): void {
  const cell = sim.cells[row]![piece.col]!;
  if (cell.incoming === piece.id) {
    cell.incoming = null;
    cell.current = piece.id;
  } else if (cell.current !== piece.id) {
    cell.current = piece.id;
  }
  piece.logicalRow = row;
}

function updateDropping(sim: DropSim, dtMs: number): void {
  const step = dtMs / FALL_MS_PER_CELL;
  const moving = sim.pieces.filter((p) => p.dropping).sort((a, b) => b.visualRow - a.visualRow);
  for (const piece of moving) {
    piece.visualRow += step;
    transferOwnership(sim, piece);
    if (piece.visualRow + 1e-4 < piece.targetRow) continue;
    piece.visualRow = piece.targetRow;
    const next = piece.targetRow + 1;
    if (next < sim.size && canReceive(sim, next, piece.col)) {
      confirmAt(sim, piece, piece.targetRow);
      startDrop(sim, piece, next);
      continue;
    }
    piece.dropping = false;
    piece.visualRow = piece.targetRow;
    confirmAt(sim, piece, piece.targetRow);
  }
}

/** Advance one frame. Returns true if anything is still dropping or queued. */
export function stepDropSim(sim: DropSim, dtMs: number): boolean {
  const dt = Math.min(Math.max(dtMs, 0), FALL_MS_PER_CELL * 0.4);
  scanDrops(sim);
  spawnAtTop(sim);
  updateDropping(sim, dt);
  return sim.pieces.some((p) => p.dropping) || sim.queues.some((q) => q.length > 0);
}

/** Catch up after a hitch without jumping more than ~0.4 cell per inner step. */
export function advanceDropSim(sim: DropSim, dtMs: number): boolean {
  const slice = 1000 / 60;
  let left = Math.min(Math.max(dtMs, 0), 80);
  let busy = true;
  while (left > 0) {
    busy = stepDropSim(sim, Math.min(slice, left));
    left -= slice;
    if (!busy) break;
  }
  return busy;
}

export function restDropPieces(sim: DropSim): void {
  for (const piece of sim.pieces) {
    piece.visualRow = piece.homeRow;
    piece.targetRow = piece.homeRow;
    piece.dropping = false;
  }
}
